# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://your_github_username.github.io/your_project_name/"

git_url = "https://github.com/your_github_username/your_project_name/tree/The default branch of your GitHub repo (usually either master or main)/"

def custom_doc_links(name): return None
